package com.devsatish.vocabo.Repository

class MediumRepository {
    private val EasywordList = listOf(

        "क्षमता" to "Ability", "त्याग देना" to "Abandon", "परित्याग" to "Abandonment",
        "पालन करना" to "Abide", "योग्यता" to "Ability", "अनुपस्थिति" to "Absence", "अनुपस्थित" to "Absent",
        "पूर्ण" to "Absolute", "सोख लेना" to "Absorb", "दुरुपयोग" to "Abuse", "स्वीकार करना" to "Accept",
        "पहुंच" to "Access", "दुर्घटना" to "Accident", "पूरा करना" to "Accomplish", "अनुसार" to "According",
        "खाता" to "Account", "सही" to "Accurate", "प्राप्त करना" to "Achieve", "मान्यता देना" to "Acknowledge",
        "अर्जित करना" to "Acquire", "सक्रिय" to "Active", "गतिविधि" to "Activity", "वास्तविक" to "Actual",
        "अनुकूल बनाना" to "Adapt", "जोड़ना" to "Add", "पता" to "Address", "समायोजित करना" to "Adjust",
        "प्रशंसा करना" to "Admire", "प्रवेश" to "Admission", "स्वीकार करना" to "Admit", "अपनाना" to "Adopt",
        "वयस्क" to "Adult", "अग्रिम" to "Advance", "लाभ" to "Advantage", "साहसिक कार्य" to "Adventure",
        "विज्ञापन करना" to "Advertise", "सलाह" to "Advice", "सलाह देना" to "Advise", "मामला" to "Affair",
        "प्रभावित करना" to "Affect", "स्नेह" to "Affection", "वहन करना" to "Afford", "डर" to "Afraid",
        "बाद" to "After", "दोपहर" to "Afternoon", "फिर से" to "Again", "खिलाफ" to "Against",
        "आयु" to "Age", "एजेंसी" to "Agency", "एजेंट" to "Agent", "सहमत होना" to "Agree",
        "समझौता" to "Agreement", "आगे" to "Ahead", "सहायता" to "Aid", "लक्ष्य" to "Aim",
        "हवा" to "Air", "विमान" to "Aircraft", "अलार्म" to "Alarm", "शराब" to "Alcohol",
        "सतर्क" to "Alert", "विदेशी" to "Foreigner", "जीवित" to "Alive", "सब" to "All",
        "अनुमति देना" to "Allow", "लगभग" to "Almost", "अकेला" to "Alone", "साथ-साथ" to "Along",
        "पहले से" to "Already", "भी" to "Also", "बदलना" to "Alter", "विकल्प" to "Alternative",
        "हालांकि" to "Although", "हमेशा" to "Always", "अद्भुत" to "Amazing", "महत्वाकांक्षा" to "Ambition",
        "के बीच" to "Among", "राशि" to "Amount",  "विश्लेषण" to "Analysis",
        "प्राचीन" to "Ancient", "कोण" to "Angle", "गुस्सा" to "Angry", "जानवर" to "Animal",
        "वार्षिक" to "Annual", "उत्तर" to "Answer", "चिंता" to "Anxiety", "कोई भी" to "Any",
        "अलग" to "Apart", "अपार्टमेंट" to "Apartment", "माफी मांगना" to "Apologize",
        "अपील" to "Appeal", "प्रकट होना" to "Appear", "उपस्थिति" to "Appearance", "सेब" to "Apple",
        "लागू करना" to "Apply", "नियुक्त करना" to "Appoint", "नियुक्ति" to "Appointment", "सराहना" to "Appreciate",
        "दृष्टिकोण" to "Approach", "उपयुक्त" to "Appropriate", "स्वीकृति" to "Approval", "मंजूरी देना" to "Approve",
        "अप्रैल" to "April", "क्षेत्र" to "Area", "बहस करना" to "Argue", "तर्क" to "Argument",
        "उठना" to "Arise", "बांह" to "Arm", "सेना" to "Army", "आसपास" to "Around",
        "व्यवस्थित करना" to "Arrange", "व्यवस्था" to "Arrangement", "गिरफ्तार करना" to "Arrest",
        "आगमन" to "Arrival","पहुंचना" to "Arrive", "कला" to "Art", "लेख" to "Article", "कृत्रिम" to "Artificial",
        "कलाकार" to "Artist", "जैसा" to "As", "राख" to "Ash", "पूछना" to "Ask",
        "सो रहा है" to "Asleep", "पहलू" to "Aspect", "इकट्ठा करना" to "Assemble", "सभा" to "Assembly",
        "मूल्यांकन करना" to "Assess", "आकलन" to "Assessment", "सहायता करना" to "Assist",
        "सहायता" to "Assistance","सहायक" to "Assistant", "सहयोगी" to "Associate",
        "संघ" to "Association",  "मान लेना" to "Assume", "आश्वस्त करना" to "Assure",
        "आश्चर्यचकित करना" to "Astonish", "वातावरण" to "Atmosphere", "संलग्न करना" to "Attach",
        "हमला करना" to "Attack", "प्रयास" to "Attempt", "भाग लेना" to "Attend", "ध्यान" to "Attention",
        "दृष्टिकोण" to "Attitude", "वकील" to "Attorney", "आकर्षित करना" to "Attract", "आकर्षण" to "Attraction",
        "विशेषता" to "Attribute", "नीलामी" to "Auction", "दर्शक" to "Audience", "अगस्त" to "August", "चाची"  to "Aunt",
        "लेखक" to "Author", "अधिकार" to "Authority", "स्वचालित" to "Automatic","उपलब्ध" to "Available", "औसत" to "Average",
        "बचना" to "Avoid", "जागना" to "Awake","पुरस्कार" to "Award", "जागरूक" to "Aware",   "जागरूकता" to "Awareness",
        "दूर" to "Away","के बारे में" to "About", "बेतुका" to "Absurd", "गाली देना" to   "Abuse", "बाद में" to "After","हवाई अड्डा" to "Airport",
        "पूर्वानुमान करना" to "Anticipate", "बेढंगा" to "Awkward","दोपहर" to "Afternoon","अभिनेता" to "Actor","सेना" to "Army",



        "बच्चा" to "Baby", "पीठ" to "Back", "बुरा" to "Bad", "थैला" to "Bag",
        "गेंद" to "Ball", "केला" to "Banana", "बैंक" to "Bank",
        "आधार" to "Base", "टोकरी" to "Basket", "स्नान" to "Bath", "बैटरी" to "Battery",
        "समुद्र तट" to "Beach", "सेम" to "Bean", "भालू" to "Bear", "हराना" to "Beat",
        "सुंदरता" to "Beauty", "बिस्तर" to "Bed", "मधुमक्खी" to "Bee",
        "पहले" to "Before", "शुरू करना" to "Begin", "पीछे" to "Behind", "घंटी" to "Bell",
        "बेल्ट" to "Belt", "बेंच" to "Bench", "सबसे अच्छा" to "Best", "बेहतर" to "Better",
        "बीच में" to "Between", "साइकिल" to "Bicycle", "बड़ा" to "Big", "बिल" to "Bill",
        "पक्षी" to "Bird", "जन्मदिन" to "Birthday", "काटना" to "Bite", "काला" to "Black",
        "कंबल" to "Blanket", "अंधा" to "Blind", "खंड" to "Block", "खून" to "Blood",
        "नीला" to "Blue", "नाव" to "Boat", "शरीर" to "Body", "उबालना" to "Boil",
        "हड्डी" to "Bone", "किताब" to "Book", "बूट" to "Boot", "सीमा" to "Border",
        "बोतल" to "Bottle", "तल" to "Bottom", "कटोरा" to "Bowl", "डिब्बा" to "Box",
        "लड़का" to "Boy", "मस्तिष्क" to "Brain", "शाखा" to "Branch", "बहादुर" to "Brave",
        "रोटी" to "Bread", "तोड़ना" to "Break", "नाश्ता" to "Breakfast", "सांस" to "Breath",
        "पुल" to "Bridge", "चमकीला" to "Bright", "लाना" to "Bring", "भाई" to "Brother",
        "भूरा" to "Brown", "ब्रश" to "Brush", "बनाना" to "Build", "जलाना" to "Burn",
        "बस" to "Bus", "व्यवसाय" to "Business", "व्यस्त" to "Busy", "लेकिन" to "But",
        "मक्खन" to "Butter", "बटन" to "Button", "खरीदना" to "Buy", "भोंकना" to "Bark",
        "स्नान करना" to "Bathe", "पीटना" to "Beat", "सुंदर" to "Beautiful", "पट्टा" to "Belt",
        "पंछी" to "Birds", "अति प्रसन्न" to "Blissful", "खिलना" to "Bloom", "बहना" to "Blow",
        "उधार लेना" to "Borrow", "निचे झुकाना" to "Bow down", "तोडना" to "Break", "बाल्टी" to "Bucket",
        "मधुमक्खी"  to "Bee","संदूक" to "Box","मक्खन" to "Butter","पीतल" to "Brass","सांड" to "Bull",
        "कुतिया" to  "Bitch","दुल्हन" to "Bride","दुलहा" to "Bridegroom",


        "बिल्ली" to "Cat", "कार" to "Car", "केक" to "Cake", "कुर्सी" to "Chair",
        "कप" to "Cup", "गाय" to "Cow", "कॉफी" to "Coffee", "चॉकलेट" to "Chocolate",
        "कंप्यूटर" to "Computer", "कैमरा" to "Camera", "शहर" to "City", "बच्चा" to "Child",
        "ठंडा" to "Cold", "बंद" to "Close", "कॉल करना" to "Call", "साफ करना" to "Clean",
        "घड़ी" to "Clock", "बादल" to "Cloud", "खाना बनाना" to "Cook", "रोना" to "Cry",
        "चढ़ना" to "Climb", "रंग" to "Color", "गोला" to "Circle", "नकल करना" to "Copy",
        "बनाना" to "Create", "आना" to "Come", "पकड़ना" to "Catch", "बदलना" to "Change",
        "काटना" to "Cut", "ढकना" to "Cover", "लागत" to "Cost", "मकई" to "Corn",
        "गिनना" to "Count", "मिलाना" to "Combine", "देश" to "Country", "संस्कृति" to "Culture",
        "तुलना करना" to "Compare", "देखभाल" to "Care", "कार्ड" to "Card", "पनीर" to "Cheese",
        "चूजा" to "Chicken", "मोमबत्ती" to "Candle", "कार्टून" to "Cartoon",
        "साफ" to "Clean", "चतुर" to "Clever", "कपड़ा पहनाना" to "Clothe", "भ्रमित करना" to "Confuse",
        "जारी रखना" to "Continue", "कवर" to "Cover", "इलाज करना" to "Cure", "अलमारी" to "Cupboard",
        "मुद्रा" to "Currency", "रिवाज" to "Custom", "साइकिल" to "Cycle", "मौका" to "Chance",
        "चुनाव" to "Choice", "कक्षा" to "Class", "साफ" to "Clear", "सर्दी" to "Cold",
        "आराम" to "Comfort", "खांसी" to "Cough", "साहस" to "Courage", "चालाक" to "Clever",
        "सामान्य" to "Common", "नियंत्रण" to "Control", "आवरण" to "Layer", "जश्न मनाना" to "Celebrate",
        "सावधान" to "Careful", "ग्राहक" to "Customer", "कंपनी" to "Company", "शताब्दी" to "Century",
        "कोशिका" to "Cell", "राजधानी" to "Capital", "कपड़ा" to "Cloth", "श्रेणी" to "Category",
        "कॉलेज" to "College", "अदालत" to "Court", "महल" to "Castle", "भीड़" to "Crowd",
        "रसोइया" to "Cook", "आदेश" to "Command", "कारण" to "Cause", "पाठ्यक्रम" to "Course",
        "जंजीर" to "Chain", "प्रमुख" to "Chief", "चुना" to "Chose", "आराम देना" to "Comfort",
        "बादलयुक्त" to "Cloudy", "शिल्प" to "Craft", "रोना" to "Crying", "ठंडा" to "Cool",
        "संघर्ष" to "Conflict", "जोड़ना" to "Connect", "कोना" to "Corner", "टक्कर" to "Crash",
        "पुष्टि करना" to "Confirm", "शास्त्रीय" to "Classic", "स्वच्छता" to "Cleanliness", "गणना करना" to "Calculate",
        "पंचांग" to "Calendar", "गाड़ी" to "Car", "प्रमाण पात्र" to "Certificate", "सस्ता" to "Cheap",
        "ठगना" to "Cheat", "डांटना" to "Chide", "बच्चे" to "Children", "गिरजाघर" to "Church",
        "ताली बजाना" to "Clap", "साफ करना" to "Clear", "कपड़े" to "Clothes", "कॉफ़ी" to "Coffee",
        "चिल्लर" to "Coins", "कंघी" to "Comb", "निकलना" to "Come out", "आत्महत्या करना" to "Commit suicide",
        "पूरा करना" to "Complete", "विजय" to "Conquest", "सहमती" to "Consent", "विचार करना" to "Contemplate",
        "पारंपरिक" to "Conventional", "पकाना" to "Cook", "दाम/लागत" to "Cost", "उत्पन्न करना" to "Create",
        "उत्सुकता" to "Curiosity","शहर" to "City","राजधानी" to "Capital","कौआ" to "Crow","ऊंट" to "Camel",
        "रसायन" to "Chemical","मुर्गा" to "Cock","भीड़" to "Crowd",

        "पापा" to "Dad", "दैनिक" to "Daily", "नुकसान" to "Damage", "नृत्य" to "Dance",
        "खतरा" to "Danger", "अंधेरा" to "Dark", "तारीख" to "Date", "बेटी" to "Daughter",
        "दिन" to "Day", "मृत" to "Dead", "सौदा" to "Deal", "प्रिय" to "Dear", "मौत" to "Death",
        "कर्ज" to "Debt", "फैसला करना" to "Decide", "निर्णय" to "Decision", "गहरा" to "Deep",
        "हार" to "Defeat", "रक्षा करना" to "Defend", "रक्षा" to "Defense", "परिभाषित करना" to "Define",
        "डिग्री" to "Degree", "देरी" to "Delay", "वितरित करना" to "Deliver", "मांग" to "Demand",
        "इनकार करना" to "Deny", "निर्भर करना" to "Depend", "वर्णन करना" to "Describe", "रेगिस्तान" to "Desert",
        "डिज़ाइन" to "Design", "इच्छा" to "Desire", "मेज" to "Desk", "विनाश" to "Destruction",
        "विवरण" to "Detail", "पता लगाना" to "Detect", "निर्धारित करना" to "Determine", "विकास करना" to "Develop",
        "उपकरण" to "Device", "संवाद" to "Dialogue", "मरना" to "Die", "आहार" to "Diet", "अंतर" to "Difference",
        "अलग" to "Different", "कठिन" to "Difficult", "खोदना" to "Dig", "रात का खाना" to "Dinner", "दिशा" to "Direction",
        "गंदगी" to "Dirt", "अक्षम" to "Disable", "असहमत होना" to "Disagree", "गायब होना" to "Disappear", "आपदा" to "Disaster",
        "अनुशासन" to "Discipline", "खोज करना" to "Discover", "चर्चा करना" to "Discuss", "बीमारी" to "Disease", "नापसंद करना" to "Dislike",
        "दूरी" to "Distance", "भेद करना" to "Distinguish", "विचलित करना" to "Distract", "विभाजित करना" to "Divide", "डॉक्टर" to "Doctor",
        "दस्तावेज" to "Document", "कुत्ता" to "Dog", "दरवाजा" to "Door", "संदेह" to "Doubt", "नीचे" to "Down",
        "घसीटना" to "Drag", "नाटक" to "Drama", "खींचना" to "Draw", "सपना" to "Dream",
        "पोशाक" to "Dress", "पीना" to "Drink", "चलाना" to "Drive", "गिरना" to "Drop", "सूखा" to "Dry",
        "धूल" to "Dust", "कर्तव्य" to "Duty", "मंद" to "Dull", "गूंगा" to "Dumb", "फेंकना" to "Throw",
        "प्रतिलिपि" to "Duplicate", "टिकाऊ" to "Durable", "अवधि" to "Duration", "सांझ" to "Dusk", "कूड़ेदान" to "Dustbin",
        "गतिशील" to "Dynamic", "डेयरी" to "Dairy", "हिम्मत करना" to "Dare", "दौड़" to "Dash",
        "डेटा" to "Data", "धोखा देना" to "Deceive", "छत" to "Deck", "सजाना" to "Decorate", "स्वादिष्ट" to "Delicious",
        "आनंद" to "Delight", "ध्वस्त करना" to "Demolish", "मांद" to "Den", "घनत्व" to "Density", "खरोंच" to "Dent",
        "रवाना होना" to "Depart", "जमा करना" to "Deposit", "उदास करना" to "Depress", "गहराई" to "Depth", "उतरना" to "Descend",
        "योग्य होना" to "Deserve", "अलग करना" to "Detach", "विस्तार से" to "Detail", "आरेख" to "Diagram", "छूट" to "Discount",
        "घृणा" to "Disgust", "पकवान" to "Dish", "प्रदर्शन" to "Display", "परेशान करना" to "Disturb", "गोता लगाना" to "Dive",
        "तलाक" to "Divorce", "दान करना" to "Donate", "दाता" to "Donor", "खुराक" to "Dose", "बिंदु" to "Point",
        "दोगुना" to "Double", "आटा" to "Dough", "पर्दा" to "Drape", "चित्र बनाना" to "Draw", "दराज" to "Drawer",
        "बहाव" to "Drift", "छेद करना" to "Drill", "गाड़ी चलाना" to "Drive", "सूखा" to "Drought", "ढोल" to "Drum",
        "बतख" to "Duck", "देय" to "Due", "द्वंद्व" to "Duel", "बौना" to "Dwarf", "निर्भर होना" to "Depend on",
        "रंगना" to "Dye", "झूलना" to "Dangle", "डेटाबेस" to "Database", "बहू" to "Daughter-in-law",
        "मलबा" to "Debris", "दशक" to "Decade", "क्षय" to "Decay", "दिसंबर" to "December",
        "हल करना" to "Decipher", "घोषणा" to "Declaration", "गिरावट" to "Decline", "सजावट" to "Decor", "समर्पित करना" to "Dedicate",
        "कटौती" to "Deduction", "हिरण" to "Deer", "दोष" to "Defect", "निश्चित" to "Definite", "विकृत करना" to "Deform",
        "मिटाना" to "Delete", "खोज करना" to "Delve", "घना" to "Dense", "चित्रण करना" to "Depict",
        "मिठाई" to "Dessert", "गंतव्य" to "Destination", "नष्ट करना" to "Destroy", "साहसी" to "Daring",
        "निर्णय,तय करना" to "Decide", "हराना" to "Defeat", "निराशा" to "Dejection", "मांग करना" to "Demand",
        "बेचैनी" to "Desperation", "मेहनती" to "Diligent", "भेदभाव" to "Discrimination", "असंतुष्ट/नाखुश" to "Dissatisfied",
        "बाँटना" to "Distribute", "तंग करना" to "Disturb", "बाँटना" to "Divide", "दरवाज़ा" to "Door", "संदेह करना" to "Doubt",
        "स्वप्न देखना" to "Dream", "सूखा" to "Drought","जिला" to "District","गधा" to "Donkey",


        "उत्सुक" to "Eager", "जल्दी" to "Early", "कमाना" to "Earn", "पृथ्वी" to "Earth",
        "आराम" to "Ease", "पूर्व" to "East", "आसान" to "Easy", "खाना" to "Eat",
        "गूंज" to "Echo", "पारिस्थितिकी" to "Ecology", "आर्थिक" to "Economic", "अर्थव्यवस्था" to "Economy",
        "किनारा" to "Edge", "संपादित करना" to "Edit", "शिक्षित करना" to "Educate", "शिक्षा" to "Education",
        "प्रभाव" to "Effect", "प्रभावी" to "Effective", "कुशल" to "Efficient", "प्रयास" to "Effort",
        "आठ" to "Eight", "या तो" to "Either", "लोचदार" to "Elastic", "बुजुर्ग" to "Elder",
        "चुनना" to "Elect", "चुनाव" to "Election", "विद्युत" to "Electric", "बिजली" to "Electricity",
        "सुंदर" to "Elegant", "तत्व" to "Element", "हाथी" to "Elephant", "ऊंचा करना" to "Elevate",
        "ग्यारह" to "Eleven", "पात्र" to "Eligible", "समाप्त करना" to "Eliminate", "अभिजात वर्ग" to "Elite",
        "अन्य" to "Else", "शर्मिंदा करना" to "Embarrass", "गले लगाना" to "Embrace", "आपातकाल" to "Emergency",
        "भावना" to "Emotion", "जोर" to "Emphasis", "रोजगार देना" to "Employ", "कर्मचारी" to "Employee",
        "नियोक्ता" to "Employer", "रोजगार" to "Employment", "खाली" to "Empty", "सक्षम करना" to "Enable",
        "अधिनियमित करना" to "Enact", "सामना करना" to "Encounter", "प्रोत्साहित करना" to "Encourage", "अंत" to "End",
        "खतरे में डालना" to "Endanger", "समर्थन करना" to "Endorse", "दुश्मन" to "Enemy", "ऊर्जा" to "Energy",
        "शामिल करना" to "Engage", "इंजन" to "Engine", "इंजीनियर" to "Engineer", "बेहतर बनाना" to "Enhance",
        "आनंद लेना" to "Enjoy", "बड़ा करना" to "Enlarge", "पर्याप्त" to "Enough", "समृद्ध करना" to "Enrich",
        "प्रवेश करना" to "Enter", "उद्यम" to "Enterprise", "मनोरंजन" to "Entertainment", "उत्साह" to "Enthusiasm",
        "संपूर्ण" to "Entire", "प्रवेश" to "Entrance", "लिफाफा" to "Envelope", "पर्यावरण" to "Environment",
        "ईर्ष्या" to "Envy", "प्रकरण" to "Episode", "समान" to "Equal", "समीकरण" to "Equation",
        "सुसज्जित करना" to "Equip", "उपकरण" to "Equipment", "समकक्ष" to "Equivalent", "युग" to "Era",
        "खड़ा करना" to "Erect", "त्रुटि" to "Error", "भागना" to "Escape", "खासकर" to "Especially",
        "निबंध" to "Essay", "आवश्यक" to "Essential", "स्थापित करना" to "Establish", "संपत्ति" to "Estate",
        "अनुमान" to "Estimate", "शाश्वत" to "Eternal", "नैतिकता" to "Ethics", "खाली करना" to "Evacuate",
        "मूल्यांकन करना" to "Evaluate", "भी" to "Even", "शाम" to "Evening", "घटना" to "Event",
        "अंततः" to "Eventually", "कभी" to "Ever", "हर" to "Every", "हर कोई" to "Everyone",
        "सबूत" to "Evidence", "बुराई" to "Evil", "विकास" to "Development", "सटीक" to "Exact",
        "बिल्कुल" to "Exactly", "जांच करना" to "Examine", "उदाहरण" to "Example", "अधिक होना" to "Exceed",
        "उत्कृष्ट" to "Excellent", "छोड़कर" to "Except", "विनिमय" to "Exchange", "उत्तेजित करना" to "Excite",
        "रोमांचक" to "Exciting", "चिल्लाना" to "Exclaim", "बाहर करना" to "Exclude", "माफ करना" to "Excuse",
        "निष्पादित करना" to "Execute", "कार्यकारी" to "Executive", "व्यायाम" to "Exercise", "प्रदर्शित करना" to "Exhibit",
        "प्रदर्शनी" to "Exhibition", "निर्वासन" to "Exile", "अस्तित्व में होना" to "Exist", "निकास" to "Exit",
        "विस्तार करना" to "Expand", "उम्मीद करना" to "Expect", "खर्च" to "Expense", "महंगा" to "Expensive",
        "अनुभव" to "Experience", "प्रयोग" to "Experiment", "विशेषज्ञ" to "Expert", "समझाना" to "Explain",
        "स्पष्टीकरण" to "Explanation", "अन्वेषण करना" to "Explore", "निर्यात करना" to "Export", "उजागर करना" to "Expose",
        "व्यक्त करना" to "Express", "बढ़ाना" to "Extend", "विस्तार" to "Extension", "व्यापक" to "Extensive",
        "सीमा" to "Extent", "बाहरी" to "External", "अतिरिक्त" to "Extra", "असाधारण" to "Extraordinary",
        "चरम" to "Extreme", "आँख" to "Eye", "भौं" to "Eyebrow", "बरौनी" to "Eyelash",
        "प्रत्यक्षदर्शी" to "Eyewitness", "उत्सुकता से" to "Eagerly", "ईमानदार" to "Earnest", "भूकंप" to "Earthquake",
        "पूर्वी" to "Eastern", "प्रतिध्वनियाँ" to "Echoes", "किफायती" to "Economical", "सनकी" to "Eccentric",
        "किनारे से" to "Edgewise", "खाद्य" to "Edible", "संपादक" to "Editor", "शिक्षक" to "Educator",
        "प्रभावी रूप से" to "Effectively", "दक्षता" to "Efficiency", "आसान" to "Effortless", "अंडा" to "Egg",
        "विस्तृत" to "Elaborate", "लोच" to "Elasticity", "विद्युत से भर देना" to "Electrify", "योग्य" to "Eligible",
        "वाक्पटु" to "Eloquent", "आरंभ करना" to "Embark", "मूर्त रूप देना" to "Embody", "प्रवासी" to "Emigrant",
        "प्रमुख" to "Eminent", "उत्सर्जित करना" to "Emit", "भावना" to "Emotional", "सहानुभूति" to "Empathy",
        "सशक्त बनाना" to "Empower", "शामिल करना" to "Encompass", "मुठभेड़" to "Encounter",
        "समर्थन" to "Endorsement", "सहनशक्ति" to "Endurance", "शत्रु" to "Enemy", "ऊर्जावान" to "Energetic",
        "लागू करना" to "Enforce", "व्यस्त" to "Engaged", "सगाई" to "Engagement", "इंजीनियर" to "Engineer",
        "खुदाई करना" to "Engrave", "सूचीबद्ध करना" to "Enlist", "ज्ञान देना" to "Enlighten", "सुनिश्चित करना" to "Ensure",
        "मनोरंजन करना" to "Entertain", "उत्साही" to "Enthusiastic", "पूरी तरह से" to "Entirely", "सौंपना" to "Entrust",
        "पर्यावरणीय रूप से" to "Environmentally", "बराबर करना" to "Equalize", "समान रूप से" to "Equally",
        "संतुलन" to "balance", "अपरदन" to "Erosion","बच निकलना" to "Escape","बराबर करना" to "Equate",
        "निबंधकार" to "Essayist",

        "कपड़ा" to "Fabric","चेहरा" to "Face","तथ्य" to "Fact","असफल होना" to "Fail","निष्पक्ष" to "Fair",
        "विश्वास" to "Faith","गिरना" to "Fall","झूठा" to "False","प्रसिद्धि" to "Fame","परिचित" to "Familiar",
        "परिवार" to "Family","प्रसिद्ध" to "Famous","पंखा" to "Fan","शौकीन" to "Fancy","शानदार" to "Fantastic",
        "दूर" to "Far","खेत" to "Farm","किसान" to "Farmer","फैशन" to "Fashion","तेज" to "Fast",
        "दोष" to "Fault", "पक्ष" to "Favor", "डर" to "Fear", "पंख" to "Feather", "विशेषता" to "Feature",
        "फरवरी" to "February", "शुल्क" to "Fee", "खिलाना" to "Feed", "महसूस करना" to "Feel", "साथी" to "Fellow",
        "महिला" to "Female", "बाड़" to "Fence", "त्यौहार" to "Festival", "कुछ" to "Few", "रेशा" to "Fiber",
        "कल्पना" to "Fiction", "मैदान" to "Field", "पंद्रह" to "Fifteen", "पांचवां" to "Fifth", "पचास" to "Fifty",
        "लड़ाई" to "Fight", "आकृति" to "Figure", "फ़ाइल" to "File", "भरना" to "Fill", "फिल्म" to "Film",
        "अंतिम" to "Final", "वित्त" to "Finance", "खोजना" to "Find", "ठीक" to "Fine", "उंगली" to "Finger",
        "समाप्त करना" to "Finish", "आग" to "Fire", "फर्म" to "Firm", "पहला" to "First", "मछली" to "Fish",
        "फिट" to "Fit", "पांच" to "Five", "ठीक करना" to "Fix", "झंडा" to "Flag", "लौ" to "Flame",
        "चमक" to "Flash", "समतल" to "Flat", "स्वाद" to "Flavor", "बेड़ा" to "Fleet", "मांस" to "Flesh",
        "उड़ान" to "Flight", "मंजिल" to "Floor", "आटा" to "Flour", "फूल" to "Flower", "उड़ना" to "Fly",
        "ध्यान केंद्रित करना" to "Focus", "मोड़ना" to "Fold", "पालन करना" to "Follow", "भोजन" to "Food", "मूर्ख" to "Fool",
        "पैर" to "Foot", "फुटबॉल" to "Football", "के लिए" to "For", "बल" to "Force", "जंगल" to "Forest",
        "भूलना" to "Forget", "माफ करना" to "Forgive", "कांटा" to "Fork", "रूप" to "Form", "औपचारिक" to "Formal",
        "पूर्व" to "Former", "किला" to "Fort", "भाग्य" to "Fortune", "आगे" to "Forward", "मिला" to "Found",
        "नींव" to "Foundation", "चार" to "Four", "मुफ्त" to "Free", "स्वतंत्रता" to "Freedom", "किनारा" to "Fringe",
        "जमाना" to "Freeze", "बार-बार" to "Frequent", "ताज़ा" to "Fresh", "दोस्त" to "Friend", "मैत्रीपूर्ण" to "Friendly",
        "दोस्ती" to "Friendship", "डराना" to "Frighten", "मेंढक" to "Frog", "से" to "From", "सामने" to "Front",
        "फल" to "Fruit", "तलना" to "Fry", "ईंधन" to "Fuel", "पूरा" to "Full", "मज़ा" to "Fun", "उन्माद" to "Frenzy",
        "कार्य" to "Function", "निधि" to "Fund", "मौलिक" to "Fundamental", "अंतिम संस्कार" to "Funeral", "मजेदार" to "Funny",
        "फर्नीचर" to "Furniture", "आगे" to "Further", "भविष्य" to "Future", "शानदार" to "Fabulous",
        "संकाय" to "Faculty", "बेहोश" to "Faint", "नकली" to "Fake", "दोष" to "Flaw", "खुशामद करना" to "Flatter",
        "मूर्ख" to "Foolish", "फलदायी" to "Fruitful", "निराश करना" to "Frustrate", "पूरा करना" to "Fulfill",
        "फ्यूज" to "Fuse", "कमजोर" to "Feeble", "झुंड" to "Flock", "कमजोर" to "Frail","खुशबू" to "Fragrance",
        "दरार" to "Fissure", "भाग जाना" to "Flee", "मना करना" to "Forbid", "कोड़े मारना" to "Flog", "मूर्खता" to "Folly",
        "घर्षण" to "Friction", "उछल-कूद करना" to "Frolic", "झाग" to "Froth", "फफूंद" to "Fungus", "संलयन" to "Fusion",
        "चोरी-छिपे" to "Furtive", "कथा" to "Fable", "रुक-रुक कर" to "Fitful","धुआं" to "Fume", "बेचैन होना" to "Fidget",
        "कमजोर" to "Flimsy", "पन्नी" to "Foil", "पदचिह्न" to "Footprint", "धैर्य" to "Fortitude", "लाना" to "Fetch",
        "गुट" to "Faction", "मुखौटा" to "Façade", "बहाना करना" to "Feign", "समापन" to "Finale", "भड़कना" to "Flare",
        "विखंडन" to "Fission", "लोककथा" to "Folklore","फुटेज" to "Footage", "दूरदर्शिता" to "Foresight",
        "भविष्यवाणी करना" to "Foretell", "मजबूत करना" to "Fortify","हड्डी टूटना" to "Fracture", "टुकड़ा" to "Fragment",
        "सामना करना" to "Face", "आकर्षित" to "Fascinated", "साथ देना" to "Favour", "काल्पनिक" to "Fictional",
        "लड़ना" to "Fight", "पाना" to "Find", "पता लगाना" to "Find out", "मजबूत" to "Firm", "भागना" to "Flee away",
        "बहना" to "Flow", "फूल" to "Flowers", "खाना" to "Food", "दबाद डालना" to "Force", "काटा" to "Fork",
        "झरना" to "Fountain", "फल" to "Fruits", "भयंकर" to "Furious", "आजादी" to "Freedom","लोमड़ी" to "Fox",
        "मक्खी" to "Fly","परिवार" to "Family","आटा" to "Flour","मोटा" to "Fat","भाग्य" to "Fate","पिता" to "Father",

        "लाभ" to "Gain", "खेल" to "Game", "बगीचा" to "Garden", "कचरा" to "Garbage", "दरवाजा" to "Gate",
        "इकट्ठा करना" to "Gather", "नरम" to "Gentle", "उपहार" to "Gift", "लड़की" to "Girl", "देना" to "Give",
        "खुश" to "Glad", "काँच" to "Glass", "लक्ष्य" to "Goal", "अच्छा" to "Good", "ग्रेड" to "Grade",
        "भव्य" to "Grand", "अंगूर" to "Grapes", "घास" to "Grass", "महान" to "Great", "हरा" to "Green",
        "बढ़ना" to "Grow", "आभारी" to "Grateful", "समूह" to "Group", "मार्गदर्शक" to "Guide", "सुरक्षा करना" to "Guard",
        "अनुमान करना" to "Guess", "च्युइंग गम" to "Gum", "बड़ा हुआ" to "Grown", "अभिवादन करना" to "Greet", "चमकना" to "Glow",
        "इशारा" to "Gesture", "लहसुन" to "Garlic", "गैरेज" to "Garage", "जुआरी" to "Gambler",
        "मुस्कान" to "Grin", "पकड़ना" to "Grasp", "पीसना" to "Grind", "उत्सव" to "Gala", "खुशी" to "Glee",
        "झलक" to "Glimpse", "घूरना" to "Gaze", "उदासी" to "Gloom", "सोना" to "Gold", "महिमा" to "Glory",
        "अपराधबोध" to "Guilt", "लाभदायक" to "Gainful", "सज्जन" to "Gentlemen", "शिकायती" to "Grumble", "प्याला" to "Goblet",
        "चमक" to "Glimmer", "खांचा" to "Groove", "पीसने का पत्थर" to "Grindstone", "तूफान" to "Gale", "चलने का तरीका" to "Gait",
        "कट" to "Gash", "निगलना" to "Gulp", "चमकना" to "Glisten", "गैलरी" to "Gallery", "गड्ढा" to "Gully",
        "छाया घर" to "Gazebo", "चकराना" to "Giddy", "चाल" to "Gambit", "प्रचुरता" to "Galore",
        "यंत्र" to "Gadget", "ढाल" to "Gradient", "पकड़ना" to "Grapple", "कपड़ा" to "Garment", "गटकना" to "Guzzle",
        "बूट" to "Gaiter", "हंस" to "Goose", "झलक" to "Glance", "दुख" to "Grief", "अभिभावक" to "Guardian",
        "तंत्र-मंत्र" to "Goblin", "जुआ खेलना" to "Gamble", "चमकना" to "Glitter", "कृपालु" to "Gracious", "अनुदान" to "Graft",
        "बवंडर" to "Gale", "ग्लाइडर" to "Glider", "चक्की" to "Grindstone", "पकड़ना" to "Grab", "प्यासा होना" to "Guzzle",
        "उत्तेजित करना" to "Goad", "भटकाना" to "Garble", "घूरना" to "Glare", "खुश" to "Gleeful", "खुशी मनाना" to "Gloat",
        "भव्यता" to "Grandeur", "बंधन" to "Gag", "हड़ताल" to "Gavel", "उकसाना" to "Goad", "समझना" to "Grasp",
        "गंभीर" to "Grim", "संघर्ष करना" to "Grapple", "श्रृंखला" to "Gamut", "दौड़ना" to "Gallop",
        "गंदगी" to "Grime", "गेज" to "Gauge", "उदासीन" to "Gloomy", "मुड़ना" to "Gnarled", "छावनी" to "Garrison",
        "शैतान" to "Gremlin", "घुमाना" to "Gyrate", "चमक" to "Glint", "गंदा" to "Grimy", "मुंह चिढ़ाना" to "Grimace",
        "चमक" to "Glare", "जाल" to "Gossamer", "महिमा करना" to "Glorify","गूंजना" to "Grunt", "पकड़ना" to "Grabble",
        "कुतरना" to "Gnaw", "महिमामंडन" to "Glorification", "गुरुत्वाकर्षण" to "Gravitational", "जूझना" to "Grapple",
        "आकर्षित होना" to "Gravitate", "पकड़ना" to "Grasping", "बड़ा बोलना" to "Grandiloquence", "रोना" to "Grizzle",
        "पीना" to "Guzzle", "जमीन" to "Ground", "मौज मस्ती" to "Gambol", "बाग़ीचा" to "Garden", "वास्तविक" to "Genuine",
        "निराशाजनक" to "Gloomy", "लक्ष्य" to "Goal", "अलविदा" to "Goodbye", "शासन करना" to "Govern",
        "बढ़ना, उपजाना" to "Grow","व्याकरण" to "Grammar",

        "खुश" to "Happy", "घर" to "House", "मदद" to "Help", "हाथ" to "Hand", "सिर" to "Head",
        "दिल" to "Heart", "घर" to "Home", "आशा" to "Hope", "गर्म" to "Hot", "ऊँचा" to "High",
        "कठिन" to "Hard", "बाल" to "Hair", "रुमाल" to "Handkerchief", "शहद" to "Honey", "घंटा" to "Hour",
        "गृहकार्य" to "Homework", "अस्पताल" to "Hospital", "इतिहास" to "History", "छुट्टी" to "Holiday", "होना" to "Happen",
        "चोट लगाना" to "Hurt", "विनम्र" to "Humble", "प्रसन्न" to "Happy", "कठोर" to "Harsh", "भारी" to "Heavy",
        "स्वस्थ" to "Healthy", "आशावादी" to "Hopeful", "सम्मान" to "Honor", "आदत" to "Habit", "आर्द्रता" to "Humidity",
        "जल्दीबाजी" to "Hasty", "सद्भावना" to "Harmony", "फसल" to "Harvest", "भागदौड़" to "Hustle", "हास्यास्पद" to "Hilarious",
        "बेबस" to "Helpless", "विरासत" to "Heritage", "नायक" to "Hero", "बेघर" to "Homeless", "मुख्य बिंदु" to "Highlight",
        "हनीमून" to "Honeymoon", "मेज़बान" to "Host", "इकट्ठा होना" to "Huddle", "जमा करना" to "Hoard",
        "जोखिम" to "Hazard", "स्वच्छता" to "Hygiene", "होलोग्राम" to "Hologram", "गलियारा" to "Hallway",
        "हिचकी" to "Hiccup", "श्रद्धांजलि" to "Homage", "सिरदर्द" to "Headache", "ध्यान देना" to "Heed", "नम्र" to "Humble",
        "सुनना" to "Hear", "जल्दी करना" to "Hasten", "पदानुक्रम" to "Hierarchy", "परिकल्पना" to "Hypothesis",
        "पुस्तिका" to "Handbook", "बाड़" to "Hedge", "बाधा" to "Hurdle", "जल्दी" to "Haste", "वंशानुगत" to "Hereditary",
        "अपमान" to "Humiliation", "आदतन" to "Habitual", "उत्पीड़न" to "Harassment", "भ्रांति" to "Hallucination",
        "समग्र" to "Holistic", "जिद्दी" to "Headstrong", "होम्योपैथी" to "Homeopathy", "व्यस्त" to "Hectic",
        "पवित्र" to "Hallowed", "गर्मी" to "Heat", "पाखंडी" to "Hypocritical", "बाधाएँ" to "Hurdles", "कठिनाई" to "Hardship",
        "हीमोग्लोबिन" to "Hemoglobin", "हेक्टेयर" to "Hectare", "घर का कामकाजी" to "Housekeeper", "बाधा दौड़" to "Hurdling",
        "विनम्रता" to "Humility", "शीर्षक" to "Headline", "खोखला" to "Hollow", "अंडा फोड़ना" to "Hatch","इतिहास" to "History",
        "अस्त-व्यस्त" to "Haphazard", "नुकसान पहुँचाना" to "Harm", "घृणा, नफरत करना" to "Hate", "नमस्ते" to "Hello", "उसके" to "Her",
        "यहाँ" to "Here", "उसके" to "Him", "मकान" to "House", "मानव" to "Human","नायक" to "Hero","घोड़ा" to "Horse",
        "मुर्गी" to "Hen","नायिका" to "Heroine",

        "बर्फ" to "Ice", "विचार" to "Idea", "आदर्श" to "Ideal", "पहचानना" to "Identify", "पहचान" to "Identity",
        "नजरअंदाज करना" to "Ignore", "बीमार" to "Illl", "अवैध" to "Illegal", "चित्रित करना" to "Illustrate", "छवि" to "Image",
        "कल्पना करना" to "Imagine", "तात्कालिक" to "Immediate", "प्रभाव" to "Impact", "महत्वपूर्ण" to "Important",
        "सुधारना" to "Improve", "जानकारी" to "Information", "में" to "In", "शामिल करना" to "Include", "वृद्धि करना" to "Increase",
        "संकेत करना" to "Indicate", "व्यक्तिगत" to "Individual", "उद्योग" to "Industry", "प्रभाव डालना" to "Influence", "सूचित करना" to "Inform",
        "प्रारंभिक" to "Initial", "पहल" to "Initiative", "आंतरिक" to "Inner", "डालना" to "Insert", "ज़ोर देना" to "Insist",
        "उदाहरण" to "Instance", "तुरंत" to "Instantly", "निर्देश" to "Instruction", "यंत्र" to "Instrument", "बीमा" to "Insurance",
        "इरादा करना" to "Intend", "रुचि" to "Interest", "दिलचस्प" to "Interesting", "अंतरराष्ट्रीय" to "International", "इंटरनेट" to "Internet",
        "साक्षात्कार" to "Interview", "परिचय कराना" to "Introduce", "निमंत्रण" to "Invitation", "शामिल करना" to "Involve", "लोहे" to "Iron",
        "द्वीप" to "Island", "मुद्दा" to "Issue", "यह" to "It", "वस्तु" to "Item", "आदर्शवाद" to "Idealism","प्रभावशाली" to "Impactful",
        "बीमारी" to "Illness", "कल्पना करना" to "Imagineer", "अधीर" to "Impatient", "संकेत करना" to "Imply",
        "आय" to "Income", "उदासीन" to "Indifferent", "अप्रत्यक्ष" to "Indirect", "अनौपचारिक" to "Informal", "प्रारंभिक अक्षर" to "Initials",
        "पूछताछ करना" to "Inquire", "जिज्ञासु" to "Inquisitive", "अंतर्दृष्टि" to "Insight", "लेखन" to "Inscription", "एकीकरण" to "Integration",
        "तीव्रता" to "Intensity", "इरादा" to "Intent", "संपर्क करना" to "Interact", "हस्तक्षेप करना" to "Interfere", "अंतराल" to "Interval",
        "अजेय" to "Invincible", "आविष्कार" to "Invention", "सूची" to "Inventory", "आमंत्रित करना" to "Invite", "कल्पना" to "Imagination",
        "तात्कालिक प्रभाव" to "Immediate effect", "असंभव" to "Impossible", "आयात" to "Import", "आवेग" to "Impulse",
        "आयकर" to "Income tax", "अनियमित" to "Irregular", "गहन" to "In-depth", "प्रवास करना" to "Immigrate",
        "महत्वपूर्ण रूप से" to "Importantly", "असमर्थ" to "Incapable", "घटना" to "Incidence", "सहन करना" to "Incur",
        "हस्तक्षेप" to "Interference", "अंतर्दृष्टि" to "Intuition", "पहल करने वाला" to "Initiative taker", "हस्तक्षेप करना" to "Intervene",
        "संक्रमण" to "Infection", "रोकना" to "Inhibit", "अखंडता" to "Integrity", "अपमान" to "Insult", "अपमानजनक" to "Insulting",
        "व्याख्या करना" to "Interpret", "धमकाना" to "Intimidate", "निवासी" to "Inhabitant", "प्रवृत्ति" to "Inclination", "खुदाई" to "Inscription",
        "आक्रमणकारी" to "Invader", "अनैच्छिक" to "Involuntary", "असुरक्षित" to "Insecure", "संधि" to "Inflection", "निष्कर्ष" to "Inference",
        "असमानता" to "Inequality", "तटस्थ" to "Impartial", "आसन्न" to "Imminent", "अवरोधक" to "Irresistible", "औजारात्मक" to "Instrumental",
        "व्याख्या" to "Interpretation", "आत्मनिरीक्षण" to "Introspection", "पूछताछ" to "Inquisition", "निवास करना" to "Inhabit",
        "उकसाना" to "Incite", "कमजोरी" to "Infirmity", "प्रभाव मूल्यांकन" to "Impact assessment", "अंतर्दृष्टिपूर्ण" to "Insightful",
        "असहिष्णु" to "Intolerant", "अनुपम" to "Irreplaceable", "अवरोधित करना" to "Intercept", "असुविधा" to "Inconvenience",
        "प्रतिरक्षा" to "Immunity", "तर्कहीन" to "Illogical", "अप्रत्यक्ष" to "Imprecise", "अनम्य" to "Inflexible", "असहनीय" to "Intolerable",
        "अनिवार्य" to "Indispensable", "आंतरिक" to "Inward","निमंत्रण देना" to "Invite","लोहा" to "Iron","कुख्यात" to "Infamous",
        "अनियमित" to "Intermittent", "बेदाग" to "Impeccable", "वृत्ति" to "Instinct", "नवाचार करना" to "Innovate", "स्थापित करना" to "Install",
        "धोखेबाज़" to "Imposter", "बाढ़ आना" to "Inundate", "निहितार्थ" to "Implication", "झुका हुआ" to "Inclined",
        "क्रोधित" to "Irate", "थोपना" to "Imposition", "अंतर्निहित" to "Inherent", "बुद्धिमत्ता" to "Intelligence", "शिलालेख" to "Inscription",
        "मध्यस्थ" to "Intermediary", "पूछताछ" to "Interrogation", "जटिल" to "Intricate", "बर्फ़" to "Ice", "बहरूपिया" to "Imposter",
        "आजाद होना" to "Independent", "निरिक्षण करना" to "Inspect", "अपमानित करना" to "Insult", "बाढ़" to "Inundation",
        "निष्कर्षहीन" to "Inconclusive",  "प्रभावित करना" to "Impress",

        "जैकेट" to "Jacket", "जेल" to "Jail", "जैम" to "Jam", "चमेली" to "Jasmine", "न्यायिक रूप से" to "Judicially",
        "जार" to "Jar", "नौकरी" to "Job", "दौड़ना" to "Jog", "जुड़ना" to "Join", "मजाक" to "Joke",
        "यात्रा" to "Journey", "न्यायाधीश" to "Judge", "जूस" to "Juice", "कूदना" to "Jump", "जूनियर" to "Junior",
        "केवल" to "Just", "खुशी" to "Happy", "जवाहरात" to "Jewel", "जेलर" to "Jailor", "खुशमिजाज" to "Jolly",
        "कूदना" to "Jumping", "उलझाना" to "Jumble", "निर्णय" to "Judgment", "संयुक्त" to "Joint",
        "विशाल" to "Jumbo", "जॉकी" to "Jockey", "जलन" to "Jealous", "पत्रकारिता करना" to "Journalize",
        "खटकना" to "Jangle", "घूमना" to "Jaunt", "चौराहा" to "Junction", "कचरा" to "Junk",
        "जूरी" to "Jury", "शब्दजाल" to "Jargon", "दौड़ना" to "Jogging", "झंकार" to "Jingle",
        "उपहास करना" to "Jeer", "धक्का देना" to "Jostle", "जौहरी" to "Jeweler", "गीदड़" to "Jackal",
        "समानांतर रखना" to "Juxtapose", "नोट करना" to "Jot", "खुशमिजाज" to "Jovial", "रसीला" to "Juicy",
        "चंचल" to "Jaunty", "बड़ा उत्सव" to "Jamboree", "जेड" to "Jade", "भाला" to "Javelin", "जश्न" to "Jubilee",
        "पहेली" to "Jigsaw", "उत्सव" to "Jamboree", "मजाकिया" to "Jester", "दरवाजे का फ्रेम" to "Jamb",
        "पत्रिका" to "Journal", "सफाई कर्मचारी" to "Janitor", "सही ठहराना" to "Justify", "विवेकी" to "Judicious",
        "रत्न" to "Jewels", "खुशी" to "Jolly", "बेचैन" to "Jittery", "थका हुआ" to "Jaded",
        "भ्रमण" to "Jaunt", "जार में रखा हुआ" to "Jarred", "फंस गया" to "Jammed", "घाट" to "Jetty",
        "गालदार" to "Jowly", "संयुक्त रूप से" to "Jointly", "जंगल" to "Jungle", "नोट करना" to "Jotting",
        "कबाड़खाना" to "Junkyard", "न्यायिक" to "Judicial", "श्राप" to "Jinx", "आनंदित" to "Joyful",
        "उत्साहित" to "Jazzed", "खटकता हुआ" to "Jangly", "कनिष्ठ" to "Junior", "जोड़ा हुआ" to "Jointed",
        "जेली" to "Jelly", "रसीला" to "Juiced", "घबराया हुआ" to "Jumpy", "धक्का देना" to "Jostling",
        "तख़्त" to "Joist", "भ्रमण" to "Junket", "बकवास करना" to "Jibber", "छोड़ना" to "Jettison",
        "जादू" to "Juju", "अवरोधक" to "Jammer", "जूसर" to "Juicer", "प्रतिस्पर्धा" to "Jockeying",
        "निर्णयात्मक" to "Judgmental", "चौंकाने वाला" to "Jarring", "बकबक करना" to "Jibber-jabber",
        "जलन" to "Jealousy", "नशेड़ी" to "Junkie","आभूषण" to "Jewellery",


        "कंगारू" to "Kangaroo", "चाकू" to "Knife", "चाबी" to "Key", "दयालु" to "Kind", "राजा" to "King",
        "ज्ञान" to "Knowledge", "रखना" to "Keep", "बच्चा" to "Kid", "रसोई" to "Kitchen", "लात" to "Kick",
        "पतंग" to "Kite", "दस्तक देना" to "Knock", "गांठ" to "Knot", "किट" to "Kit", "शांत रहो" to "Keep calm",
        "अपहरण करना" to "Kidnap", "केतली" to "Kettle", "कीबोर्ड" to "Keyboard", "दयालुता" to "Kindness",
        "साम्राज्य" to "Kingdom", "चुम्बन" to "Kiss", "ज्ञानी" to "Knowledgeable",  "लात मारना" to "Kicking",
        "चुम्बन करना" to "Kissing", "बिल्ली का बच्चा" to "Kitten", "तंदुरुस्त" to "fit", "चाबी का गुच्छा" to "Keychain",
        "केचप" to "Ketchup", "घुंघराला" to "Kinky", "कर्म" to "Karma", "आधार" to "base",  "जानना" to "Know",

        "श्रम" to "Labor", "महिला" to "Lady", "झील" to "Lake", "भूमि" to "Land", "भाषा" to "Language",
        "बड़ा" to "Large", "अंतिम" to "Last", "हंसना" to "Laugh", "छोड़ना" to "Leave", "पैर" to "Leg",
        "पत्र" to "Letter", "जीवन" to "Life", "प्रकाश" to "Light", "पसंद करना" to "Like", "सूची" to "List",
        "जीना" to "Live", "लंबा" to "Long", "देखना" to "Look", "खोना" to "Lose", "प्यार" to "Love",
        "दोपहर का भोजन" to "Lunch", "भाग्यशाली" to "Lucky", "स्तर" to "Level", "पाठ" to "Lesson", "तर्क" to "Logic",
        "विलासिता" to "Luxury", "पत्ता" to "Leaf", "रेखा" to "Line", "उठाना" to "Lift", "कड़ी" to "Link",
        "शुरू करना" to "Launch", "पुस्तकालय" to "Library", "उधार देना" to "Lend", "सीमा" to "Limit", "स्थानीय" to "Local",
        "तार्किकता" to "Logic", "दीपक" to "Lamp", "श्रमिक" to "Laborer", "हंसी" to "Laughter", "सुनने योग्य" to "Listenable",
        "जीवनशैली" to "Lifestyle", "हल्का" to "Lighter", "योजना" to "Layout", "झुकना" to "Lean", "सुंदर" to "Lovely",
        "चाटना" to "Lick", "कूदना" to "Leap", "फीता" to "Lace", "इच्छा" to "Lust", "वकील" to "Lawyer",
        "कूदने वाला" to "Leapfrog", "वफादार" to "Loyal", "शोक करना" to "Lament", "पागल" to "Lunatic",
        "भव्य" to "Lavish", "ताला" to "Latch", "वफादार व्यक्ति" to "Loyalist", "लोरी" to "Lullaby", "तरल" to "Liquid",
        "लुभाना" to "Lure", "खाता" to "Ledger", "अक्षांश" to "Latitude", "विरासत" to "Legacy", "कचरा" to "Litter",
        "सुस्ती" to "Lethargy", "सामान" to "Luggage", "बुनाई करना" to "Loom", "वंश" to "Lineage",
        "झील" to "Lagoon", "मशहूर व्यक्ति" to "Luminary", "कानूनी" to "Legal","शौचालय" to "Lavatory",
        "प्रभाव" to "Leverage", "अकेला" to "Lonesome", "चमकदार" to "Luminous", "चीरना" to "Lacerate",
        "घातक" to "Lethal", "चमक" to "Luster", "पार्श्व" to "Lateral","लाभ" to "Leverage","सुस्त" to "Languid",
        "अकारण" to "Licentious", "परिश्रम करना" to "Labour", "सीढ़ी" to "Ladder", "औरत" to "Lady", "हँसना" to "Laugh",
        "सीखना" to "Learn", "पत्ते" to "Leaves", "पसंद" to "Like", "सुनना" to "Listen", "रहना" to "Live",
        "ताला" to "Lock", "देखभाल करना" to "Look after", "हिम्मत हारना" to "Lose patience", "चमकीला" to "Luminous",
        "दोपहर का खाना" to "Lunch","कमल" to "Lotus",

        "मशीन" to "Machine", "जादू" to "Magic", "मेल" to "Mail", "बनाना" to "Make", "आदमी" to "Man",
        "कई" to "Many", "नक्शा" to "Map", "बाजार" to "Market", "मास्क" to "Mask", "मामला" to "Matter",
        "भोजन" to "Meal", "अर्थ" to "Mean", "मापना" to "Measure", "दवा" to "Medicine", "मिलना" to "Meet",
        "पिघलना" to "Melt", "सदस्य" to "Member", "याददाश्त" to "Memory", "पुरुष" to "Men", "खुश" to "Merry",
        "संदेश" to "Message", "विधि" to "Method", "मध्य" to "Middle", "दूध" to "Milk", "मन" to "Mind",
        "मिनट" to "Minute", "चूकना" to "Miss", "मिलाना" to "Mix", "क्षण" to "Moment", "पैसा" to "Money",
        "महीना" to "Month", "अधिक" to "More", "चलना" to "Move", "पहाड़" to "Mountain", "मुँह" to "Mouth",
        "चूहा" to "Mouse", "संगीत" to "Music", "अवश्य" to "Must", "रहस्यमय" to "Mysterious", "सतर्क" to "Mindful",
        "बनाए रखना" to "Maintain", "अद्भुत" to "Magnificent", "बहुमत" to "Majority", "तंत्र" to "Mechanism", "क्षणिक" to "Momentary",
        "पदक" to "Medal", "एकाधिकार" to "Monopoly", "मूड" to "Mood", "उल्लेख करना" to "Mention", "नैतिक" to "Moral",
        "मॉडल" to "Model", "बिकाऊ" to "Marketable", "परिमाण" to "Magnitude", "प्रेरणा" to "Motivation", "मील का पत्थर" to "Milestone",
        "मॉड्यूल" to "Module", "बढ़ाना" to "Magnify", "औसत" to "Mediocre", "संगीतात्मक" to "Melodic", "अनिवार्य" to "Mandatory",
        "शहीद" to "Martyr", "शरारत" to "Mischief", "चमत्कार" to "Miracle", "आंदोलन" to "Movement", "प्रवासी" to "Migrant",
        "महाराज" to "Majesty", "उग्रवादी" to "Militant", "अद्भुत" to "Marvellous", "निगरानी करना" to "Monitor",
        "पुरुषत्व" to "Masculine", "परिपक्वता" to "Maturity", "बहुसांस्कृतिक" to "Multicultural", "सामग्री" to "Material", "पौराणिक कथाएँ" to "Mythology",
        "मिशन" to "Mission", "मृत्यु दर" to "Mortality", "रखरखाव" to "Maintainability", "कम करना" to "Minimize", "गतिशीलता" to "Mobility",
        "गलत समझना" to "Misinterpret", "विधि विज्ञान" to "Methodology", "शानदार" to "Magnificent",
        "मैराथन" to "Marathon", "स्मारक" to "Monument", "आदेश" to "Mandate", "सक्रियता" to "Mobilization","बाजार" to "Marketplace",
        "ध्यान" to "Meditation", "सक्रिय करना" to "Mobilize", "बौना" to "Minuscule", "गुणा करना" to "Multiply","भव्य" to "Majestic",
        "शहादत" to "Martyrdom", "धुंधला" to "Murky", "मशीन मिस्त्री" to "Machinist","मास्क पहने हुए" to "Masked",
        "विकृत" to "Misshapen", "ध्यानात्मक" to "Meditative", "उलझाना" to "Muddle","मुख्यधारा" to "Mainstream",
        "दुष्ट" to "Malevolent", "जादूगर" to "Magician", "विधिपूर्वक" to "Methodical",

        "माप" to "Measure", "आदर्श" to "Model", "ढाला" to "Mold",
        "माइक्रोफोन" to "Microphone", "मशरूम" to "Mushroom", "प्रवास करना" to "Migrate", "मध्यस्थता करना" to "Mediate",
        "पदक" to "Medallion", "चंचल" to "Mercurial", "मधुर" to "Melodious",
        "मेनू" to "Menu", "पतंगा" to "Moth", "मिथक" to "Myth", "चुम्बक" to "Magnet",
        "बहुलता" to "Multiplicity", "छिपा हुआ" to "Masked", "पौराणिक" to "Mythical", "भाड़े का सैनिक" to "Mercenary",
        "उपमा" to "Metaphor", "एकल संवाद" to "Monologue", "शवगृह" to "Mortuary", "प्रवीणता" to "Mastery",
        "भीड़" to "Multitude", "स्मारक" to "Memorial","मुख्य द्वार" to "Main gate",
        "अभिव्यक्ति" to "Manifestation", "अनेक" to "Many", "शादी करना" to "Marry", "बात" to "Matter", "दवाई" to "Medicine",
        "दवाइयाँ" to "Medicines", "ध्यान देना" to "Mind","दूरध्वनि यंत्र" to "Mobile", "चाँद" to "Moon", "सुबह" to "Morning",
        "मस्जिद" to "Mosque", "चाल" to "Move","घोड़ी" to "Mare","मांस" to "Meat","संगीत" to "Music","श्रीमान" to "Mr","श्रीमती" to "Mrs",

        "नाम" to "Name", "राष्ट्र" to "Nation", "प्रकृति" to "Nature", "पास" to "Near", "जरूरत" to "Need",
        "नया" to "New", "अच्छा" to "Nice", "रात" to "Night", "संख्या" to "Number", "नोट" to "Note",
        "अगला" to "Next", "अब" to "Now", "दोपहर" to "Noon", "कुछ नहीं" to "Nothing", "कभी नहीं" to "Never",
        "जाल" to "Net", "समाचार" to "News", "नाखून" to "Nail", "पड़ोसी" to "Neighbor", "सामान्य" to "Normal",
        "नोटबुक" to "Notebook", "पोषक तत्व" to "Nutrient", "नस" to "Nerve", "नोटिस" to "Notice", "अतीत की यादें" to "Nostalgia",
        "संज्ञा" to "Noun", "वर्णन" to "Narrative", "आवश्यकता" to "Necessity", "मार्गदर्शन करना" to "Navigate", "पोषण करना" to "Nurture",
        "उपेक्षा करना" to "Neglect", "वार्ता" to "Negotiation", "शूरवीर" to "Noble", "स्थान" to "Niche", "अतीत की यादों में खोया" to "Nostalgic",
        "नामित करना" to "Nominate", "सूचित करना" to "Notify", "पोषण करना" to "Nurturing", "शोरगुल वाला" to "Noisy",
        "धारणा" to "Notion", "उपन्यास" to "Novel", "पोषित" to "Nurtured", "संबंध" to "Nexus", "संकीर्ण" to "Narrow",
        "झपकी" to "Nap", "बिना रुके" to "Nonstop","गैर-लाभकारी" to "Nonprofit","राष्ट्रव्यापी" to "Nationwide",
        "नेटवर्क" to "Network", "आवश्यक बनाना" to "Necessitate", "बारीकी" to "Nuance", "तटस्थ" to "Neutral",
        "उल्लेखनीय" to "Noteable", "साफ-सुथरा" to "Neat","स्थानीय" to "Native", "पड़ोसी" to "Neighbors","कुशल" to "Nifty",
        "पोषण करने वाला" to "Nurturer", "नाखून" to "Nail", "बारीकी" to "Nicety","अनिवार्यतः" to "Necessarily",

        "चप्पू" to "Oar", "कसम" to "Oath", "वस्तु" to "Object", "देखना" to "Observe", "प्राप्त करना" to "Obtain",
        "कब्जा करना" to "Occupy", "प्रस्ताव देना" to "Offer", "कार्यालय" to "Office", "आधिकारिक" to "Official", "अक्सर" to "Often",
        "पुराना" to "Old", "खोलना" to "Open", "संचालक" to "Operator", "राय" to "Opinion", "अवसर" to "Opportunity",
        "विपरीत" to "Opposite", "विकल्प" to "Option", "आदेश" to "Order", "सामान्य" to "Ordinary", "अंग" to "Organ",
        "संगठन" to "Organization", "मूल" to "Origin", "मूलभूत" to "Original", "बाहर" to "Outside","अत्यधिक" to "Outrageous",
        "ऊपर" to "Over", "पार करना" to "Overcome", "अधिक होना" to "Overflow", "अधिक वजन" to "Overweight",
        "बहुत खुश" to "Overjoyed", "बादलों से ढका हुआ" to "Overcast", "पहुंच" to "Outreach", "आक्रोश" to "Outrage", "उत्पादन" to "Output",
        "परिधान" to "Outfit", "पिकनिक" to "Outing", "रूपरेखा" to "Outline", "बाहर का व्यक्ति" to "Outlaw", "बाहरी व्यक्ति" to "Outsider",
        "परिणाम" to "Outcome", "संख्या में अधिक होना" to "Outnumber", "पुराना हुआ" to "Outdated", "स्पष्टवादी" to "Outspoken",
        "अंडाकार" to "Oval", "अत्यंत खुश करना" to "Overjoy", "बादल से ढका हुआ" to "Overcast", "औंस" to "Ounce", "विस्फोट" to "Outburst",
        "बाह्य स्रोत से लेना" to "Outsource", "ऊपर" to "Overhead", "अधिक बोझ" to "Overload", "अभिभूत करना" to "Overwhelm",
        "पलटना" to "Overturn", "आगे" to "Onward", "मालिक" to "Owner", "जारी" to "Ongoing",  "अप्रचलित" to "Outdated",
        "ओवरलैप करना" to "Overlap", "सुसज्जित" to "Outfitted", "सर्वोत्तम" to "Optimal", "पेशा" to "Occupation",
        "ओजोन" to "Ozone", "दायित्व" to "Obligation", "बाधा" to "Obstacle", "प्रेक्षक" to "Observer", "जुनून" to "Obsession",
        "नष्ट करना" to "Obliterate", "प्राप्त करने योग्य" to "Obtainable", "कुंद" to "Obtuse", "आक्रामक" to "Offensive",
        "संतान" to "Offspring", "ऑफलाइन" to "Offline", "स्पष्ट" to "Overt", "अधिक आंकलन करना" to "Overestimate",
        "पराजित करना" to "Overpower", "अति प्रतिक्रिया देना" to "Overreact", "प्रस्ताव" to "Overture", "उत्कृष्ट" to "Outstanding",
        "भारी होना" to "Outweigh", "अस्वीकार करना" to "Overrule", "पहुँच" to "Outreach", "घटित होना" to "Occur", "रुकावट" to "Obstacle",
        "जिम्मेदारी" to "Obligation", "स्पष्ट" to "Obvious", "उद्देश्य" to "Objective", "रोकना" to "Obstruct", "गंध" to "Odor",
        "अपमान करना" to "Offend", "क्षतिपूर्ति" to "Offset", "छूट" to "Omission","विरोध करना" to "Oppose", "सर्वोत्तम" to "Optimum",
        "संचालित करना" to "Operate","कार्यात्मक" to "Operative", "खुलापन" to "Openness", "उत्पत्ति देने वाला" to "Originator",
        "बहाव" to "Overflow", "नजरअंदाज करना" to "Overlook", "प्राथमिकता देना" to "Overriding","बहिष्कृत" to "Outcast",
        "पुनः लेखन करना" to "Overwrite", "अति उत्साही" to "Overzealous", "ऑक्सीकरण करना" to "Oxidize",
        "लक्ष्य" to "Objective", "सजग" to "Observant", "अनियोजित" to "Offhand", "अत्यधिक खुश" to "Overjoyed",
        "व्यय" to "Outlay", "आज्ञा मानना" to "Obey", "नारंगी" to "Orange", "आज्ञा देना" to "Order", "हाव-भाव" to "Overture",
        "संतरा" to "Orange","बैल" to "Ox","नारंगी" to "Orange",

        "पृष्ठ" to "Page", "दर्द" to "Pain", "रंग" to "Paint", "कागज" to "Paper", "माता-पिता" to "Parent",
        "पार्क" to "Park", "पार्टी" to "Party", "पास करना" to "Pass", "मरीज" to "Patient", "भुगतान करना" to "Pay",
        "शांति" to "Peace", "लोग" to "People", "उत्तम" to "Perfect", "प्रदर्शन करना" to "Perform", "स्थान" to "Place",
        "योजना" to "Plan", "पौधा" to "Plant", "खेलना" to "Play", "जेब" to "Pocket", "बिंदु" to "Point",
        "गरीब" to "Poor", "शक्ति" to "Power", "अभ्यास" to "Practice", "तैयार करना" to "Prepare", "वर्तमान" to "Present",
        "कीमत" to "Price", "छापना" to "Print", "समस्या" to "Problem", "उत्पाद" to "Product", "कार्यक्रम" to "Program",
        "परियोजना" to "Project", "वादा" to "Promise", "सुरक्षा करना" to "Protect", "गर्वित" to "Proud", "प्रदान करना" to "Provide",
        "सार्वजनिक" to "Public", "प्रकाशित करना" to "Publish", "खींचना" to "Pull", "धक्का देना" to "Push", "पहेली" to "Puzzle",
        "रंगना" to "Paint", "गुजरना" to "Pass", "छिप-छिपकर देखना" to "Peep", "कलम" to "Pen", "फ़ोन" to "Phone",
        "तीर्थयात्री" to "Pilgrim", "तकिया" to "Pillow", "गुलाबी" to "Pink", "रोपना" to "Plant","कृपया" to "Please",
        "हल चलाना" to "Plough", "मटका" to "Pot", "झपटना" to "Pounce", "प्रशंसा करना" to "Praise","प्रार्थना करना" to "Pray",
        "सटीक" to "Precise", "तैयारी करना" to "Prepare", "दबाना, दबाव देना" to "Press", "बहाना करना" to "Pretend",
        "उन्नति करना" to "Progress", "वादा करना" to "Promise", "समझदार" to "Prudent", "सजा देना" to "Punish", "रखना" to "Put",
        "धान" to "Paddy","दाल" to "Pulse","राजकुमार" to "Prince",

        "गुणवत्ता" to "Quality", "प्रश्न" to "Question", "तेज" to "Quick", "शांत" to "Quiet", "काफी" to "Quite",
        "रानी" to "Queen", "तेजी" to "Quickness", "उद्धरण" to "Quote", "बुझाना" to "Quench",
        "उद्धरण" to "Quotation", "खोज" to "Quest", "कतार" to "Queue", "खदान" to "Quarry",
        "चौक" to "Quarters", "क्विज" to "Quiz", "बुझाने योग्य नहीं" to "Quenchless", "संगरोध" to "Quarantine", "प्रश्नवाचक" to "Quizzical",

        "दौड़" to "Race", "बारिश" to "Rain", "इंद्रधनुष" to "Rainbow", "पढ़ना" to "Read", "तैयार" to "Ready",
        "असली" to "Real", "कारण" to "Reason", "प्राप्त करना" to "Receive", "याद रखना" to "Remember", "दोहराना" to "Repeat",
        "रिपोर्ट" to "Report", "आराम" to "Rest", "वापस आना" to "Return", "सही" to "Right", "जोखिम" to "Risk",
        "कमरा" to "Room", "गुलाब" to "Rose", "नियम" to "Rule", "दौड़ना" to "Run", "पका" to "Ripe","पहुँचना" to "Reach",
        "पढना" to "Read", "पहचानना" to "Recognize", "लाल" to "Red", "इन्कार करना" to "Refuse","याद करना" to "Remember",
        "हटाना" to "Remove", "पछताना" to "Repent", "जबाब देना" to "Reply", "अनुरोध करना" to "Request","अंगुठी" to "Ring",
        "त्यागपत्र देना" to "Resign", "आदर करना" to "Respect", "आराम करना" to "Rest", "अवकाश पाना" to "Retire", "चावल" to "Rice",
        "अंगूठी" to "Ring", "नदी" to "River", "सड़क" to "Road", "बर्बाद करना" to "Ruin", "विनाशकारी" to "Ruinous","शासन करना" to "Rule",

        "क़ुर्बानी देना" to "Sacrifice", "दुखी" to "Sad", "वही" to "Same", "संतुष्ट/तृप्त" to "Satisfied", "बचाना" to "Save",
        "विद्यालय" to "School", "खोजना" to "Search", "देखना" to "See", "चुनना" to "Select", "बेचना" to "Sell",
        "भेजना" to "Send", "सेवा करना" to "Serve", "अस्त होना" to "Set", "सिलाई करना" to "Sew", "दाढ़ी बनाना" to "Shave",
        "मुस्कुराना" to "Shine", "दुकान" to "Shop", "चिल्लाना" to "Shout", "गाना" to "Sing", "आकाश" to "Sky",
        "गुलाम" to "Slave", "सोना" to "Sleep", "धीमा" to "Slow", "छोटा" to "Small", "मुस्कुराना" to "Smile",
        "धूम्रपान करना" to "Smoke", "इसलिए" to "So", "साबुन" to "Soap", "सिसकना" to "Sob", "अकेला" to "Solitary",
        "समाधान करना" to "Solve", "माफ़ कीजिये" to "Sorry", "बोलना" to "Speak", "खर्च करना, व्यतीत करना" to "Spent",
        "बरबाद करना" to "Spoil", "चम्मच" to "Spoon", "खड़ा होना" to "Stand", "तारा" to "Star", "आरम्भ करना" to "Start",
        "भुखमरी" to "Starvation", "ठहरना" to "Stay", "अभी तक/अभी भी" to "Still", "रुकना" to "Stop", "संघर्ष करना" to "Struggle",
        "छात्र" to "Student", "अध्ययन करना" to "Study", "ग्रसित होना, पीड़ित होना" to "Suffer", "सूरज" to "Sun", "अन्धविश्वास" to "Superstition",
        "मिठाई" to "Sweets", "तैरना" to "Swim", "झूला" to "Swing", "सुरक्षित" to "Safe", "नाव चलाना" to "Sail",
        "बिक्री" to "Sale", "नमक" to "Salt", "बालू" to "Sand", "कहना" to "Say", "स्कूल" to "School",
        "सेट करना" to "Set", "आकार" to "Shape", "साझा करना" to "Share", "चमकना" to "Shine", "छोटा" to "Short",
        "दिखाना" to "Show", "बंद करना" to "Shut", "सरल" to "Simple", "डूबना" to "Sink", "बैठना" to "Sit",
        "आकार" to "Size", "बर्फ" to "Snow", "भिगोना" to "Soak", "नरम" to "Soft", "ठोस" to "Solid",
        "दक्षिण" to "South", "स्थान" to "Space", "विशेष" to "Special", "गति" to "Speed", "खर्च करना" to "Spend",
        "आत्मा" to "Spirit", "वसंत" to "Spring", "शुरू करना" to "Start", "राज्य" to "State", "रहना" to "Stay",
        "कदम" to "Step", "स्टॉक" to "Stock", "दुकान" to "Store", "तूफान" to "Storm", "शैली" to "Style",
        "सफलता" to "Success", "ऐसा" to "Such", "अचानक" to "Sudden", "गर्मी" to "Summer", "समर्थन" to "Support",
        "निश्चित" to "Sure", "सतह" to "Surface", "आश्चर्य" to "Surprise", "मीठा" to "Sweet", "तेज" to "Swift",
        "प्रणाली" to "System", "सुरक्षा" to "Safety", "सफल होना" to "Succeed", "सुझाव देना" to "Suggest", "चिल्लाना" to "Scream",
        "संतुष्ट करना" to "Satisfy", "दुःख" to "Sorrow", "खोज" to "Search", "संतोष करना" to "Satisfy", "ईमानदार" to "Sincere",
        "कमी" to "Scarcity", "रणनीति" to "Strategy", "नमूना" to "Sample", "बलिदान" to "Sacrifice", "वेतन" to "Salary",
        "संतोष" to "Satisfaction", "आपूर्ति" to "Supply", "संघर्ष" to "Struggle", "सुरक्षित करना" to "Secure", "संकेत" to "Signal",
        "निलंबित करना" to "Suspend", "ढलान" to "Slope", "कथन" to "Statement", "स्टॉकिंग" to "Stocking", "अनुभाग" to "Section",
        "सेटअप" to "Setup", "भाई-बहन" to "Sibling", "गोलाकार" to "Sphere", "जिद्दी" to "Stubborn", "सदस्यता" to "Subscription",
        "आंकड़े" to "Statistics", "आश्रय" to "Shelter", "निचोड़ना" to "Squeeze", "स्वच्छता" to "Sanitation", "उपग्रह" to "Satellite",
        "चुप्पी" to "Silence", "फिसलन" to "Slippery", "स्रोत" to "Source", "प्रदर्शनी" to "Showcase", "पाठ्यक्रम" to "Syllabus",
        "स्वाभाविक" to "Spontaneous", "संश्लेषण" to "Synthesis", "उत्तेजना" to "Stimulation", "चयन करना" to "Select", "शानदार" to "Spectacular",
        "छात्रवृत्ति" to "Scholarship", "भंडारण" to "Storage", "तस्वीर" to "Snapshot", "स्थिति" to "Situation", "घटाना" to "Subtract",
        "पर्याप्त" to "Sufficient", "दृश्य" to "Scenery", "अनुकरण" to "Simulation", "संक्षेप में बताना" to "Summarize", "संतृप्ति" to "Saturation",
        "समरूपता" to "Symmetry", "स्कैंडल" to "Scandal", "सिंड्रोम" to "Syndrome", "दबाना" to "Suppress",
        "जीवित रहना" to "Survive", "डाँटना" to "Scold", "सर्वेक्षण" to "Survey", "बनाए रखना" to "Sustain", "समर्पण करना" to "Surrender",
        "शिखर" to "Summit", "प्रतीक" to "Symbol", "विद्वान" to "Scholar", "अनुदान" to "Subsidy", "सलामी देना" to "Salute",
        "नारा" to "Slogan", "परखना" to "Scrutinize", "अंकुरित होना" to "Sprout", "मापने योग्य" to "Scalable", "कमी" to "Shortage",
        "ढाल" to "Shield", "पदार्थ" to "Substance", "उत्तेजित करना" to "Stimulate", "समानार्थक शब्द" to "Synonym","चाँदी" to "Silver",
        "बालू" to "Sand","महोदय" to "Sir","मानक" to "Standard","वर्तनी" to "Spelling",

        "मेज" to "Table", "प्रतिभा" to "Talent", "बात करना" to "Talk", "ऊँचा" to "Tall", "वश में करना" to "Tame",
        "स्वाद" to "Taste", "कर" to "Tax", "सिखाना" to "Teach", "आँसू, फाड़ना" to "Tear", "बताना" to "Tell",
        "मंदिर" to "Temple", "तनावग्रस्त, काल" to "Tense", "धन्यवाद" to "Thank", "वह" to "That",
        "उनका" to "Their", "उन्हें" to "Them", "वहाँ" to "There", "ये" to "These", "वे" to "They",
        "सोचना" to "Think", "चीज" to "Thing", "यह" to "This", "हालांकि" to "Though", "विचार" to "Thought",
        "हजार" to "Thousand", "धागा" to "Thread", "खतरा" to "Threat", "तीन" to "Three", "के माध्यम से" to "Through",
        "फेंकना" to "Throw", "इस प्रकार" to "Thus", "समय" to "Time", "टायर" to "Tire", "शीर्षक" to "Title",
        "के लिए" to "To", "आज" to "Today", "कल" to "Tomorrow", "जीभ" to "Tongue", "आज रात" to "Tonight",
        "उपकरण" to "Tool", "दांत" to "Tooth", "शीर्ष" to "Top", "छूना" to "Touch", "की ओर" to "Toward",
        "नगर" to "Town", "ट्रेन" to "Train", "अनुवाद करना" to "Translate", "पेड़" to "Tree", "परेशानी" to "Trouble",
        "ट्रक" to "Truck", "सच्चा" to "True", "भोजन" to "Meal", "नल" to "Tap",
        "चाय" to "Tea", "शिक्षक" to "Teacher", "चिढ़ाना" to "Tease", "धन्यवाद" to "Thank You", "तब" to "Then",
        "धमकाना" to "Threaten", "कंजूस" to "Thrifty", "थनका ठनकना" to "Thunder", "कठिन/मुश्किल" to "Tough", "तौलिया" to "Towel",
        "बर्ताव करना" to "Treat", "कोशिश करना" to "Try", "लेना" to "Take", "टीम" to "Team", "परीक्षण" to "Test",
        "साथ में" to "Together", "भी" to "Too", "यात्रा करना" to "Travel", "मोड़" to "Turn", "प्रकार" to "Type",
        "कुल" to "Total", "व्यापार" to "Trade", "कार्य" to "Task", "टेलीविजन" to "Television", "तापमान" to "Temperature",
        "तकनीक" to "Technique", "टिकट" to "Ticket", "परंपरा" to "Tradition", "खजाना" to "Treasure", "सुरंग" to "Tunnel",
        "टैबलेट" to "Tablet", "क्षेत्र" to "Territory", "सिद्धांत" to "Theory", "समयरेखा" to "Timeline", "रंगमंच" to "Theater",
        "त्रासदी" to "Tragedy", "यातायात" to "Traffic", "लेन-देन" to "Transaction", "बदलना" to "Transform", "पारदर्शी" to "Transparent",
        "भरोसा" to "Trust", "सच" to "Truth", "ट्यूटर" to "Tutor", "लक्ष्य" to "Target",
        "प्रौद्योगिकी" to "Technology", "प्रलोभन" to "Temptation", "शोधपत्र" to "Thesis", "स्वर" to "Tone",
        "प्रवृत्ति" to "Trend", "श्रद्धांजलि" to "Tribute", "ट्रॉफी" to "Trophy", "मोड़" to "Twist",
        "टोकन" to "Token", "पाठ" to "Text", "उष्णकटिबंधीय" to "Tropical", "परिवहन" to "Transport",
        "विशेषता" to "Trait", "सहिष्णुता" to "Tolerance", "टोल" to "Toll", "अवधि" to "Term",
        "टेम्पलेट" to "Template", "दूरबीन" to "Telescope", "रणनीति" to "Tactic", "अंगूठा" to "Thumb", "झुकना" to "Tilt",
        "उपचार" to "Treatment", "टब" to "Tub", "बनावट" to "Texture", "पाठ्यपुस्तक" to "Textbook", "टैंक" to "Tank",
        "साफ-सुथरा" to "Tidy", "शाश्वत" to "Timeless", "संक्रमण" to "Transition", "यात्रा" to "Trip", "सुर" to "Tune",
        "चमकना" to "Twinkle", "कछुआ" to "Turtle", "वर्जना" to "Taboo", "परीक्षण" to "Trial", "तनाव" to "Tension",
        "आतंक" to "Terror", "छंटाई" to "Trim", "घास" to "Turf", "गिनती" to "Tally", "टॉफ़ी" to "Toffee",
        "थिम्बल" to "Thimble", "हंगामा" to "Tumult", "उत्तेजना" to "Thrill", "धड़कना" to "Throb", "धीरे-धीरे चलना" to "Trot",
        "उलझना" to "Tangle", "नीरसता" to "Tedious", "टुकड़ा" to "Tidbit", "धड़धड़ाना" to "Thump", "कांटेदार पौधा" to "Thistle",
        "टैक" to "Tack", "बताना" to "Tattle", "झुनझुनी" to "Tingle", "झाड़ी" to "Thicket",
        "विष" to "Toxin", "गवाही" to "Testimony","दल" to "Team","बाघ" to "Tiger",

        "ऊपर" to "Up", "इस्तेमाल करना" to "Use", "छाता" to "Umbrella", "चाचा/मामा" to "Uncle",
        "नीचे" to "Under", "समझना" to "Understand", "विश्वविद्यालय" to "University", "यूनिफॉर्म" to "Uniform", "अद्वितीय" to "Unique",
        "दुखी" to "Unhappy", "जब तक" to "Until", "अपलोड करना" to "Upload", "शहरी" to "Urban", "उपयोगी" to "Useful",
        "सामान्य" to "Usual", "बर्तन" to "Utensil", "अंतिम" to "Ultimate", "उठाना" to "Uplift","तत्काल" to "Urgent", "अवांछित" to "Unwanted",
        "अनिश्चित" to "Uncertain", "दुर्भाग्यपूर्ण" to "Unfortunate", "असामान्य" to "Uncommon", "अनिच्छुक" to "Unwilling",
        "खोलना" to "Unfold", "हंगामा" to "Uproar", "एकीकृत करना" to "Unify", "प्रकट करना" to "Unveil", "बेकार" to "Useless",
        "असामान्य" to "Unusual", "उजागर करना" to "Uncover", "अपराजेय" to "Unbreakable", "अस्तव्यस्त" to "Untidy",
        "बिना छुए" to "Untouched", "अप्रत्याशित" to "Unpredictable", "अस्थिर" to "Unstable", "असंभावित" to "Unlikely",
        "धूमधाम" to "Uproarious", "अप्रचलित" to "Unconventional", "रेखांकित करना" to "Underline", "परेशान करना" to "Upset",
        "आग्रह करना" to "Urge", "अनियंत्रित" to "Unrestrained", "विकसित होना" to "Unfolding", "पूरी तरह से" to "Utterly",
        "अविश्वसनीय" to "Unreliable", "अनजाने में" to "Unintended", "अवांछनीय" to "Unwelcome",  "आराम करना" to "Unwind",
        "असंभव" to "Unthinkable", "उलझन सुलझाना" to "Untangle", "बनाए रखना" to "Uphold","अपरिचित" to "Unfamiliar",
        "अनियंत्रित" to "Uncontrolled","कम आँकना" to "Underestimate", "वंचित" to "Underprivileged", "निर्विवाद" to "Undisputed",
        "असहनीय" to "Unbearable", "अप्राकृतिक" to "Unnatural", "अनुपयोगी" to "Unused",
        "खोलना" to "Unfurl", "सुलझाना" to "Unravel", "असमान" to "Uneven","खोदकर निकालना" to "Unearth", "अपरिवर्तित" to "Unchanged",
        "प्लग हटाना" to "Unplug", "अतुलनीय" to "Unimaginable", "अप्रवेशनीय" to "Unapproachable", "निर्जन" to "Uninhabited",
        "निर्विवाद" to "Unquestionable", "बिना तैयारी के" to "Unrehearsed", "सरल" to "Uncomplicated",
        "निरपेक्ष" to "Unbiased", "रहने योग्य नहीं" to "Uninhabitable","अविवाहित" to "Unmarried",

        "डगमगाना" to "Vacillate", "सब्ज़ी" to "Vegetables", "गाड़ी" to "Vehicle", "बरतन" to "Vessels",
        "अनुभवी" to "Veteran", "तंग करना" to "Vex", "मूल्य" to "Value", "विविधता" to "Variety", "दौरा" to "Visit",
        "वाहन" to "Vehicle", "आवाज" to "Voice", "बहुत" to "Many", "दृश्य" to "View", "विशाल" to "Vast",
        "भिन्न होना" to "Vary", "वचन" to "Vow", "मान्यता देना" to "Validate", "जीवंत" to "Vivid",
        "उद्यम" to "Venture", "विजय" to "Victory", "स्वयंसेवक" to "Volunteer", "महत्वपूर्ण" to "Vital", "दृश्यात्मक" to "Visual",
        "वोट" to "Vote", "लाभदायक स्थिति" to "Vantage", "अभिमान" to "Vanity", "भंवर" to "Vortex", "कंपन" to "Vibration",
        "जीवंत" to "Vibrant", "वैन" to "Van", "चिपचिपा" to "Viscous", "कविता" to "Verse", "वेस्ट" to "Vest",
        "गारंटी देना" to "Vouch", "खलनायक" to "Villain", "मान्य करना" to "Validate", "चक्र" to "Vortex", "दृष्टि-रक्षक" to "Visor",
        "प्रतिशोध" to "Vengeance", "दृष्टि" to "Vision", "अस्पष्टता" to "Vagueness", "पुराना" to "Vintage", "जीवन शक्ति" to "Vitality",
        "विशालता" to "Vastness", "विष" to "Venom", "जीवंतता से" to "Vividly",
        "पेंट" to "Varnish", "पेशा" to "Vocation", "स्वैच्छिक" to "Voluntary", "मूल्यांकन" to "Valuation",
        "भिन्नता" to "Variance", "अवशेष" to "Vestige", "कमजोर" to "Vulnerable", "पॉलिश किया हुआ" to "Varnished", "हिंसक" to "Violent",
        "शून्य" to "Void", "कंठ" to "Vocal", "चिपचिपापन" to "Viscosity", "सत्यता" to "Veracity", "सतर्कता" to "Vigilance",
        "गाँववाला" to "Villager", "चिपचिपा" to "Viscid", "साहसिक कार्य" to "Venture", "व्यवहार्य" to "Viable", "श्रद्धा" to "Veneration",
        "व्यर्थता" to "Vanity", "अग्रणी" to "Vanguard", "छुट्टी" to "Vacation", "उल्लंघन" to "Violation","गायब होना" to "Vanish",
        "वैक्सीन" to "Vaccine", "कंपन करना" to "Vibrate","भाप" to "Vapor", "उपराजा" to "Viceroy", "मूल्यवान" to "Valued",
        "शब्दावली" to "Vocabulary", "जीवन्तता" to "Vividness", "निर्णय" to "Verdict", "व्यवहार्यता" to "Viability", "नकाब" to "Veil",

        "प्रतीक्षा करना" to "Wait", "चलना" to "Walk", "चाहना" to "Want", "चेतावनी देना" to "Warn", "धोना, साफ़ करना" to "Wash",
        "बर्बाद करना" to "Waste", "पानी" to "Water", "सप्ताह" to "Week", "रोना" to "Weep", "तुलना" to "Weigh",
        "गेहूँ" to "Wheat", "पहिया" to "Wheel", "कानाफूसी करना" to "Whisper", "जितना" to "Win", "खिड़की" to "Window",
        "मनोहर" to "Winsome", "काम करना" to "Work", "लायक/योग्य" to "Worth", "चाहेंगे" to "Would", "लिखना" to "Write",
        "इंतज़ार करना" to "Wait", "देखना" to "Watch", "जीतना" to "Win", "शब्द" to "Word", "गर्म" to "Warm",
        "स्वागत करना" to "Welcome", "अच्छा" to "Well", "इच्छा करना" to "Wish", "अद्भुत" to "Wonderful", "दुनिया" to "World",
        "चिंता करना" to "Worry", "वजन" to "Weight", "विजेता" to "Winner", "पैदल मार्ग" to "Walkway", "जंगली" to "Wild","विधवा" to "Widow",
        "पत्नी" to "Wife","गेहूँ" to "Wheat","ऊन" to "Wool","लकड़ी" to "Wood",

        "साल" to "Year", "पिला" to "Yellow", "हाँ" to "Yes", "कल" to "Yesterday", "तुम्हारी" to "Your",
        "वर्ष" to "Year", "पीला" to "Yellow", "तुम/आप" to "You", "युवा" to "Young", "आपका" to "Your",
        "अभी तक" to "Yet", "उत्पादन करना" to "Yield", "ज्यूँ करना" to "Yawn", "यॉट" to "Yacht", "यार्ड" to "Yard",
        "स्वादिष्ट" to "Yummy", "युवा" to "Youth", "योग" to "Yoga", "जोड़ी" to "Yoke", "लजीज" to "Yummy",
        "तरसना" to "Yearn", "वहां" to "Yonder", "चिल्लाना" to "Yell",

        "शून्य" to "Zero", "ज़ेब्रा" to "Zebra", "ज़िप" to "Zip", "क्षेत्र" to "Zone","ज़ूम" to "Zoom",


        "गुच्छा" to "Bunch","झुंड" to "Flock","समिति" to "Committee","भीड़" to "Mob","संन्यासी" to "Monk","भेड़ा" to "Ram",
        "भेड़ी" to "Ewe","महोदया" to "Madam","विधुर" to "Widower","कवि" to "Poet","आत्मा" to "Soul","सम्मान" to "Respect",
        "वकील" to "Lawyer","अखबार" to "newspaper","उत्सुकता" to "Curiosity","झपटना" to "Pounce","हाव-भाव" to "Overture",
        "सुखा" to "Drought","मौज-मस्ती" to "Gambol","तीर्थयात्री" to "Pilgrim","बहरूपिया" to "Imposter","अकेला" to "Solitary",
        "भुखमरी" to "Starvation","कंजूस" to "Thrifty","साहसी" to "Daring","पता लगाना" to "Detect","बेतुका" to "Absurd",
        "मेहनती" to "Diligent","विजय" to "Conquest","पागल" to "Lunatic","भयंकर" to "Furious","फुर्तीला" to "Nimble",
        "बेढंग" to "Awkward","सटीक" to "Precise","निराशा" to "Dejection","सहमती" to "Consent","अतिप्रसन" to "Blissful",
        "अन्धविश्वासी" to "Superstition","भेदभाव" to "Discrimination","पारंपरिक" to "Conventional","बेचैनी" to "Desperation",
        "आकर्षित" to "Fascinated","वास्तविक" to "Genuine","निराशाजनक" to "Gloomy","समझदार" to "Prudent","नौसिखिया" to "Novice",
        "अनुभवी" to "Veteran","काल्पनिक" to "Fictional","मनोहर" to "Winsome","चमकीला" to "Luminous","अस्त-व्यस्त" to "Haphazard",
        "विचार करना" to "Contemplate",

// Changed- 05-11-2025.

    )

    fun getList(): List<Pair<String, String>> = EasywordList
}